### ISSUE TITLE
Implement API Integration and data extraction

### ISSUE THREAD

**Issue by illumimarty** [AND101-Pod20/UnsplashClient#1]
To-Do
- [x] Branch off from `main` and set up project environment
- [x] Make API request and handle response
- [x] Parse API response for desired data
- [x] Extract relevant items from API response
- [x] Implement functionality to use extracted data, results to be seen on Logcat

Endpoints to use:
- `GET /search/photos`
    - User can view a list of images based on a search prompt
    - User can view details of the image, such as author, date the photo taken
- `GET /photos/:id`
    - User can download a particular image to their device

Unsplash API Documentation: [Link](https://unsplash.com/documentation)
Note: I recommend using Postman to validate the API response before adding it to the project.

**Comment by AdityaBoghara** [comment]
Extracted relevant data from api and created a pull request. Ready to MERGE
